version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every day
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      # Check for updates managed by NPM once a day
      interval: 'daily'
